# Generated by Django 3.0.7 on 2020-06-05 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
